services:
  postgres:
    image: postgres:9.6
    container_name: moutsti_database
    restart: always
    environment:
      POSTGRES_USER: user_moutsti
      POSTGRES_PASSWORD: moutsti2024
      POSTGRES_DB: db_api_moutsti_orders
    ports:
      - "5432:5432"
    volumes:
      - database_moutsti_data:/var/lib/postgresql/data
    networks:
      - moutsti-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: moutsti_rabbitmq
    restart: always
    ports:
      - "5672:5672" # Porta para comunicação AMQP
      - "15672:15672" # Porta para o painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: moutsti
      RABBITMQ_DEFAULT_PASS: moutsti2024
    networks:
      - moutsti-network

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ] # Configuração para persistência
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - moutsti-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540" # Porta para acessar o RedisInsight
    networks:
      - moutsti-network
    depends_on:
      - redis

volumes:
  database_moutsti_data:
  redis_data:
    driver: local

networks:
  moutsti-network:
    driver: bridge
