name: Build and Deploy API Moutsti Orders

on:
  push:
    branches:
      - main  # Rodar o workflow quando houver push na branch main
      - develop  # Rodar o workflow quando houver push na branch main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar o JDK 17 para a build do projeto Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Build do projeto Spring Boot usando Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Set up Docker Buildx (necessário para multi-plataforma)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DigitalOcean Container Registry (DOCR)
      - name: Log in to Digital Ocean Container Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build e Push da Imagem para o Microservice Register
      - name: Build and push Register Service
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=${{ github.ref_name }}
          IMAGE_TAG=registry.digitalocean.com/repository-api-moutsti-orders:${BRANCH_NAME}-$TIMESTAMP
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG